# Deploys website to Firebase Hosting.

name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  generator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache/Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn depedencies
        # if: steps.cache-restore.outputs.cache-hit != 'true' This gives error code 127
        run: yarn install

      - name: Generte PDF files
        working-directory: generator
        run: node main.js

      - name: Upload PDFs for web app to use
        uses: actions/upload-artifact@v2
        with:
          name: PDF_Data
          path: generator/build/pdf

  build:
    runs-on: ubuntu-latest
    needs: generator
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache/Restore
        uses: actions/cache@v2
        id: cache-restore
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn depedencies
        # if: steps.cache-restore.outputs.cache-hit != 'true' This gives error code 127
        run: yarn install

      - name: Download PDFs to public directory
        uses: actions/download-artifact@v2
        with:
          name: PDF_Data
          path: public/pdf

      - name: Setup production environment
        run: echo $ENV_PRODUCTION > .env.production
        env:
          ENV_PRODUCTION: ${{ secrets.ENV_PRODUCTION }}

      - name: Build app
        run: yarn build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run deploy
